apiVersion: workload.nephio.org/v1alpha1
kind: NFDeployment
metadata: # kpt-merge: upf-example/upf-example
  name: upf-core
  namespace: sdcore5g-upf
  annotations:
    internal.kpt.dev/upstream-identifier: 'workload.nephio.org|NFDeployment|upf-example|upf-example'
spec:
  provider: upf.sdcore5g.io
  interfaces:
  - name: n3
    ipv4:
      address: 172.3.128.0/17
      gateway: ""
    vlanID: 2
  - name: n4
    ipv4:
      address: 172.1.128.0/17
      gateway: ""
    vlanID: 3
  - name: n6
    ipv4:
      address: 172.6.128.0/17
      gateway: ""
    vlanID: 4
  networkInstances:
  - name: vpc-internal
    interfaces:
    - n4
  - name: vpc-internet
    dataNetworks:
    - name: internet
      pool:
      - prefix: 172.6.129.0/24
    interfaces:
    - n6
  - name: vpc-ran
    interfaces:
    - n3
  capacity:
    maxDownlinkThroughput: 5G
    maxUplinkThroughput: 5G
